#*************** Config Module Related Configurations ***************#
### If user MySQL as datasource:
spring.datasource.platform: mysql

### Count of DB:
db.num: 1

### Connect URL of DB:
db.url.0: jdbc:mysql://192.168.56.1:3306/nacos?useSSL=false&characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&serverTimezone=UTC
db.user: root
db.password: 123456
