
#======================================#
#========== Server settings ===========#
#======================================#

server:

  port: 8971
  servlet:
    context-path: ~
  tomcat:
    uri-encoding: UTF-8
    
#======================================#
#========== Cloud settings ============#
#======================================#

# 服务注册
eureka:

  # 实例设置
  instance:
    # 实例主机名称
    hostname: 127.0.0.1
    # 实例是否允许使用IP
    preferIpAddress: false
    # 实例状态监控参数
    statusPageUrlPath: ${server.servlet.context-path}/project/default
    healthCheckUrlPath: ${server.servlet.context-path}/actuator/health

  # 客户端设置
  client:
    # 注册中心地址（集群时指定另外一个注册中心地址）
    serviceUrl.defaultZone: http://127.0.0.1:8970/eureka/

#======================================#
#========== Spring settings ===========#
#======================================#

spring:

  # 应用程序名称
  application:
    name: jeesite-cloud-config

  # 当前环境名称（注意：不可设置为 test 它是单元测试专用的名称）
  profiles:
    active: native
  
  # 分布式配置中心
  cloud:
    config:
      server:
      
        # 使用本地配置文件
        native:
          searchLocations: classpath:jeesite-cloud-43
          
        # 使用Git储存配置文件
        git: 
          uri: https://gitee.com/thinkgem/config.git
          username: ~
          password: ~
          default-label: master
          search-paths: jeesite-cloud-43
    
    # Consul 服务发现
    consul:
      host: 127.0.0.1
      port: 8500
      discovery:
        hostname: 127.0.0.1
        preferIpAddress: false
        healthCheckPath: ${server.servlet.context-path}/actuator/health
        healthCheckInterval: 15s
          
  # 消息队列服务
#  rabbitmq:
#    host: 192.168.56.106
#    port: 5672
#    username: admin
#    password: admin123

  # 关闭横幅
  main:
    bannerMode: "off"
    
# 日志配置
logging:
  config: classpath:config/logback-spring.xml
        
#======================================#
#========== Project settings ==========#
#======================================#
