
#======================================#
#========== Server settings ===========#
#======================================#

server:

  port: 8980
  servlet:
    context-path: /js
  tomcat:
    uri-encoding: UTF-8
    
#======================================#
#========== Cloud settings ============#
#======================================#

# 服务注册
eureka:

  # 实例设置
  instance:
    # 实例主机名称
    hostname: 127.0.0.1
    # 实例是否允许使用IP
    preferIpAddress: false
    # 实例状态监控参数
    statusPageUrlPath: ${server.servlet.context-path}
    healthCheckUrlPath: ${server.servlet.context-path}/actuator/health

  # 客户端设置
  client:
    # 注册中心地址（集群时指定另外一个注册中心地址）
    serviceUrl.defaultZone: http://${eureka.instance.hostname}:8970/eureka/

#======================================#
#========== Spring settings ===========#
#======================================#

spring:

  # 网关路由配置
  cloud:
    gateway:
      defaultFilters:
        - PreserveHostHeader
      routes:
        # 测试模块1
        - id: test
          uri: lb://jeesite-cloud-module-test1/js/a/test1
          predicates:
            - Path=/js/a/test1/**
        # 测试模块2
        - id: test
          uri: lb://jeesite-cloud-module-test2/js/a/test2
          predicates:
            - Path=/js/a/test2/**
        # 基础权限模块
        - id: main
          uri: lb://jeesite-cloud-module-main/js
          predicates:
            - Path=/js/**
  
  # 应用程序名称
  application:
    name: jeesite-cloud-gateway

  # 当前环境名称（注意：不可设置为 test 它是单元测试专用的名称）
  profiles:
    active: default
  
  # 关闭 Spring Boot Banner 打印
  main:
    bannerMode: "off"

# 日志配置
logging:
  config: classpath:config/logback-spring.xml
    
#======================================#
#========== Project settings ==========#
#======================================#
