server:

  port: 8980
  context-path: /js
  tomcat:
    uri-encoding: UTF-8

spring:

  profiles:
    # 当前激活环境名称，（注意：不可设置为 test 它是单元测试用的环境名称）
    active: default
    
  main:
    banner-mode: "off"
