
#============================#
#===== Database sttings =====#
#============================#

# 数据库连接
jdbc: 

  # Mysql 数据库配置
  type: mysql
  driver: com.mysql.jdbc.Driver
  url: jdbc:mysql://127.0.0.1:3306/jeesite4?useSSL=true&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
  username: root
  password: 123456
  testSql: SELECT 1
  
  # Oracle 数据库配置
#  type: oracle
#  driver: oracle.jdbc.driver.OracleDriver
#  url: jdbc:oracle:thin:@127.0.0.1:1521/orcl
#  username: jeesite
#  password: jeesite
#  testSql: SELECT 1 FROM DUAL

#============================#
#===== System settings ======#
#============================#

# 产品或项目名称、版本、版权年份
productName: JeeSite Demo
productVersion: V4.0
copyrightYear: 2018

# 软件提供商公司或个人名称
companyName: ThinkGem

#是否演示模式
demoMode: false
