    
#======================================#
#========== Cloud settings ============#
#======================================#

# 服务注册
eureka:

  # 实例设置
  instance:
    # 实例主机名称
    hostname: 10.0.2.15
    # 实例是否允许使用IP
    preferIpAddress: false

  # 客户端设置
  client:
    # 注册中心地址（集群时指定另外一个注册中心地址）
    serviceUrl.defaultZone: http://10.0.2.15:8970/eureka/

#======================================#
#========== Spring settings ===========#
#======================================#

spring:

  # 当前环境名称（注意：不可设置为 test 它是单元测试专用的名称）
  profiles:
    active: git
  
  # 分布式配置中心
  cloud:
    config:
      discovery:
        enabled: true
        serviceId: jeesite-cloud-config
        
      # 分布式配置中心
      server:
        # 使用Git储存配置文件
        git: 
          uri: https://gitee.com/thinkgem/config.git
          username: ~
          password: ~
          default-label: master
          search-paths: jeesite-cloud-50
          
    # Consul 服务发现
    consul:
      host: 10.0.2.15
      port: 8500
      discovery:
        hostname: 10.0.2.15
        preferIpAddress: false
        
  # 消息队列服务
#  rabbitmq:
#    host: 192.168.56.106
#    port: 5672
#    username: admin
#    password: admin123
