
# 服务注册
eureka:

  # 实例设置
  instance:
    # 实例是否允许使用IP
    preferIpAddress: true

  # 客户端设置
  client:
    # 注册中心地址（集群时指定另外一个注册中心地址）
    serviceUrl.defaultZone: http://172.17.0.2:8970/eureka/

