
#======================================#
#========== Spring settings ===========#
#======================================#

spring:
  
  # 数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/jeesite?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    
  # Redis 连接参数 （RedisProperties）
  redis:
    host: 127.0.0.1
    port: 6379
    ssl: false
    database: 0
    password: 1234
    timeout: 2000
