
# 数据库连接
jdbc: 
  
  # Mysql 数据库配置
  type: mysql
  driver: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://192.168.56.1:3306/jeesite?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=CONVERT_TO_NULL&serverTimezone=Asia/Shanghai
  username: jeesite
  password: jeesite
  testSql: SELECT 1

  # 数据库连接池配置
  pool:
  
    # 初始化连接数
    init: 1
    # 最小连接数
    minIdle: 3
    # 最大连接数
    maxActive: 20

  # JTA 分布式事务
  jta:
    enabled: true

#======================================#
#========== Spring settings ===========#
#======================================#

spring:
    
  # Redis 连接参数 （RedisProperties）
  redis:
    host: 192.168.56.1
    port: 6379
    ssl: false
    database: 0
    password: 1234
    timeout: 2000
    lettuce:
      pool:
        # 最大空闲连接数
        maxIdle: 3
        # 最大活动连接数
        maxActive: 20

# MyBatis 相关
mybatis:

  # Mapper文件刷新线程
  mapper:
    refresh:
      enabled: false

# 文件相关
file:

  # 文件上传根路径，设置路径中不允许包含“userfiles”，在指定目录中系统会自动创建userfiles目录，如果不设置默认为contextPath路径
  baseDir: /data