
#productName: JeeSite Gateway

#======================================#
#========== Spring settings ===========#
#======================================#

spring:
  cloud:
  
    # 流量防卫兵
    sentinel:
      transport:
        port: 9311
        dashboard: 127.0.0.1:9311
      # 更改 csp 日志位置
      log:
        dir: ${user.home}/logs/csp
        switch-pid: true
      # 流量防卫兵 Nacos 数据源
      datasource:
        ds2.nacos:
          server-addr: 127.0.0.1:8848
          data-id: ${spring.application.name}-sentinel
          group-id: jeesite-cloud-yml
          rule-type: flow

    # 网关路由配置
    gateway:
      defaultFilters:
        - PreserveHostHeader
      routes:
      
        # 测试模块1
        - id: test1
          uri: lb://jeesite-cloud-module-test1
          predicates:
            - Path=/js/a/test1/**,/js/a/jeesite-cloud-module-test1/**,/js/static/modules/test1/**
            
        # 测试模块2
        - id: test2
          uri: lb://jeesite-cloud-module-test2
          predicates:
            - Path=/js/a/test2/**,/js/a/jeesite-cloud-module-test2/**,/js/static/modules/test2/**
            
        # 测试模块3
        - id: test3
          uri: lb://jeesite-cloud-module-test3
          predicates:
            - Path=/js/a/test3/**,/js/a/jeesite-cloud-module-test3/**,/js/static/modules/test3/**
            
        # 业务流程模块
        - id: bpm
          uri: lb://jeesite-cloud-module-bpm
          predicates:
            - Path=/js/a/bpm/**,/js/bpm/**,/js/inner/api/bpm/**,/js/static/modules/bpm/**,/js/static/htmltags/bpm/**,/js/a/jeesite-cloud-module-bpm/**,/js/a/oa/oaLeave/**
            
        # 基础权限模块
        - id: core
          uri: lb://jeesite-cloud-module-core
          predicates:
            - Path=/js/**

#======================================#
#========== Project settings ==========#
#======================================#

management.endpoint.gateway.enabled: false
