
#productName: JeeSite Core
  
#======================================#
#========== System settings ===========#
#======================================#

# 任务调度（个人版+）
job:
  enabled: true
  
#======================================#
#========= Framework settings =========#
#======================================#

# Web 相关
web:
  
  # 核心模块的Web功能（仅作为微服务时设为false）
  core: 
    enabled: true
    
#======================================#
#========== Project settings ==========#
#======================================#
