
#======================================#
#========== Server settings ===========#
#======================================#

server:

  port: 8981
    
#======================================#
#========== Cloud settings ============#
#======================================#

# 服务注册
eureka:

  # 实例设置
  instance:
    # 实例主机名称
    hostname: 10.0.2.15
    # 实例是否允许使用IP
    preferIpAddress: false

  # 客户端设置
  client:
    # 注册中心地址（集群时指定另外一个注册中心地址）
    serviceUrl.defaultZone: http://10.0.2.15:8970/eureka/

#======================================#
#========== Spring settings ===========#
#======================================#

spring:
  
  # 分布式配置中心
  cloud:
    config:
      discovery:
        enabled: true
        serviceId: jeesite-cloud-config
        
    # Consul 服务发现
    consul:
      host: 10.0.2.15
      port: 8500
      discovery:
        hostname: 10.0.2.15
        preferIpAddress: false
        
    # 服务注册和配置
    nacos:
      discovery:
        server-addr: 10.0.2.15:8848
      config:
        server-addr: 10.0.2.15:8848
        file-extension: yml
        group: jeesite-cloud-42
        ext-config:
          - data-id: application.yml
            group: jeesite-cloud-42
